services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: flask_library_management
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - library_management_net

  postgres:
    image: postgres:14
    container_name: postgres_library_management
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_management_net

volumes:
  postgres_data:

networks:
  library_management_net:
    driver: bridge
