version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres_library_management
    env_file: # Explicitly specify the .env file
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_management_net

volumes:
  postgres_data:

networks:
  library_management_net:
    driver: bridge
