swagger: "2.0"
info:
  description: "This is a sample API for the Library Management System."
  version: "1.0.0"
  title: "Library API"
host: "localhost:5000"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /users:
    get:
      summary: "Get all users"
      description: "Returns a list of users."
      produces:
        - "application/json"
      responses:
        200:
          description: "A list of users."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
  /books:
    get:
      summary: "Get all books"
      description: "Returns a list of books."
      produces:
        - "application/json"
      responses:
        200:
          description: "A list of books."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
  Book:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      author:
        type: "string"
